### ISSUE TITLE
Original Bernstein Chess Program

### ISSUE THREAD

**Issue by pgalbraith** [mdoege/PyTuroChamp#1]
Hi thanks for sharing these engines.  I'm curious how you were able to implement the Bernstein program, did you have original source or a tape copy to work from?

**Comment by mdoege** [comment]
It would be great if the original source code or binary would be rediscovered, but I don't think that has happened yet. So I had to use the Bernstein paper ("A chess playing program for the IBM 704") and its example games.

Getting the Plausible Move Table right based on the text description alone is very difficult, so the Python engine is an approximation.

**Comment by pgalbraith** [comment]
Got it.  Thanks again for sharing these efforts!
