### ISSUE TITLE
batch-file for PyturoChamp - OS: Windows 7 SP1 (32&64 bit)

### ISSUE THREAD

**Issue by yellow-panther** [mdoege/PyTuroChamp#1]
Hello Martin,

I use current version **Arena GUI** www.playwitharena.com for tournaments between WB/UCI-compatible chess engines, e.g. like https://github.com/thomasahle/sunfish/archive/master.zip (Sunfish) or https://github.com/stannous/shatranj/archive/master.zip (Shatranj) . Both are XB/WB compatible and written in Python language. I have installed Python v2.7.14 for Windows and created with **Notepad** https://notepad-plus-plus.org/ two batch files **python -u shatranj118.py -xboard** respectively **python -u xboard.py**
[Shatranj - Sunfish Python WB.zip](https://github.com/mdoege/PyTuroChamp/files/1502949/Shatranj.-.Sunfish.Python.WB.zip)

Can you build such a batch file for PyturoChampI too and host it on GitHub, please? I am not a programmer, only tester of chess programs. This batch file then could replace the python executable and a (necessary?) commandline-parameter e.g. like xboard.

**Comment by mdoege** [comment]
Here is a .bat file: https://github.com/mdoege/PyTuroChamp/blob/master/ptc.bat
