### ISSUE TITLE
Can't download the windows binary

### ISSUE THREAD

**Issue by pgalbraith** [mdoege/PyTuroChamp#2]
I'm trying to download the windows binary for turochamp but it seems google drive permissions on it are blocking download.

![2020-10-20 23_21_09-Window](https://user-images.githubusercontent.com/19995454/96669409-2c23d780-132b-11eb-857d-2cde5f047dab.png)

**Comment by mdoege** [comment]
The binary files have been restored now.

P.S. Note that these binaries only contain PTC, not the other engines.
