### ISSUE TITLE
Turing engine by ChessBase (Freeware)

### ISSUE THREAD

**Issue by yellow-panther** [mdoege/PyTuroChamp#2]
cf. 
[Turing CB Native.zip](https://github.com/mdoege/PyTuroChamp/files/1502958/Turing.CB.Native.zip) for a Fritz GUI 5.32 ChessBase or later http://www.top-5000.nl/dl.htm?file=dl/fritz532.zip 
[Turing logos 130x65.zip](https://github.com/mdoege/PyTuroChamp/files/1502962/Turing.logos.130x65.zip)

**Comment by mdoege** [comment]
Yes, I know this implementation exists. I don't have Fritz though, and no intention of buying it either...
