### ISSUE TITLE
Problem with PyTuroChamp and pypy

### ISSUE THREAD

**Issue by tosca07** [mdoege/PyTuroChamp#3]
Hi Martin,

not really a PyTuroChamp issue but you were so kind to offer some help.

Because of slow performance of python 3.6 with PyTuroChamp (several minutes per move) I would like to run it with pypy.

I have downloaded pypy3 and use this instead of python36.

But when I start ptc_xboard with pypy3 it says 
"Import error: no module named "chess".

I have python-chess installed via pip before and it works for python36 but not pypy3.

Do you know if I have to install chess again for pypy and how?

Thanks
Dirk

**Comment by mdoege** [comment]
Like it says on my repo page under "Improving performance by using PyPy". Basically first you need to install pip for pypy, then you use that pip to install python-chess.

Note that in my example I am adding the "--user" flag, so pip and python-chess get installed into the current user's directory. You don't have to, it's just that on Linux it is usually better to separate things installed by the Linux package manager from other package managers such as pip. You will probably need to use a different path to run pip than .local/bin/, depending on your operating system.

```
pypy3 -m ensurepip --user
~/.local/bin/pip3 install python-chess --user
```

**Comment by tosca07** [comment]
I now have installed pip3 and when trying to install python-chess via pip3 it says that this already exists (I assume it references to my Installation done with the original pip?

But when I execute “pip3 list’ it shows me the chess module.

But I still get the import error: no module named chess.

So I think there is a problem with the original o thin-chess Installation that pip3 thinks that it already exists and does not install it correctly for pypy3.

Hmmm.  I think I give up as I just want to use it and I am not an expert (I use Windows 10 ).

But anyway thanks for helping
Dirk

**Comment by mdoege** [comment]
You're welcome! 😃
