### ISSUE TITLE
Is it possible to use PyTuroChamp in picochess as a chess engine?

### ISSUE THREAD

**Issue by tosca07** [mdoege/PyTuroChamp#4]
Hello Martin,

Again not really an issue (your PyTuroChamp works even if it is slow ;-) 
Don‘ know if you know about picochess project https://github.com/jromang/picochess (developed mainly at the moment by Jürgen (LocutusOfPenguin). It’s is a complete chess programm implenentation for the electronic dgt chess board together with a dgt chess clock on a raspberry pi. 

As far as I can understand it is also based on python chess and they just include serveral precompiled uci chess engines for arm processor. 

Maybe by chance you have experience how to include your PyTuroChamp engine in picochess?

Thanks
Dirk

**Comment by mdoege** [comment]
I have not played around with picochess, but I am aware of its existence. It looks like the engines are supposed to be binaries, so calling a Python script might be tricky. Maybe what is needed is a wrapper executable that pretends to be an UCI engine to python-chess but calls Python and the script itself.

I think it would be better to create an issue in the picochess repo and ask about support for Python-based engines.

**Comment by tosca07** [comment]
Thanks again for your quick and kind answer, Martin.
Yes, I will open an issue in picochess group.
Thanks, Dirk

**Comment by tosca07** [comment]
Hallo Martin,
good news: I was able to include PyTuroChamp with PICOCHESS as an UCI chess engine (a little bit tricky but in principle it works - even for other Python code!!!

But there is one issue: I can only play two moves - then the engine crashes or is in an endless loop.

By analyzing the pico chess log files I think I nailed the problem: 
I think there is one UCI command missing or not fully implemented in PyTuroChamp.

I has something to do with how pico chess communicates the user move to the engine.

It looks like pico chess always communicates the move with the UCI command

POSITION FEN MOVES 

Implemeted in PyTuroChamp is only POSITION STARTPOS MOVES thats why only the first user move is correctly transferred (first call is  POSITION STARTPOS MOVES) but from the second move on pico chess tries to transfer the move to the engine by calling POSITION FEN MOVES eg.

Here after playing e2e4 e7e5 the next move should be a2a4 which is communicated as follows:

position fen rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e3 0 1 moves a2a4

Unfortunately I was unable to enhance ptc_xboard.py - I tried but had no luck as we would have to parse the argument string to get the fen part and moves part and process it afterwards.

I don't have any python know how and I just tried to add:

 elif 'position fen moves' in l:
                        mm = l.splitt()[3:]
                        fen = l.splitt()[2:]
                        fromfen(fen)
                        for mo in mm:
                                d.push_uci(mo)

but that does not work. To get the FEN string from the middle of the argument the parser needs to be a little bit complexes I guess.

Maybe you can help with implementing the POSITION FEN MOVES command for UCI .

Do you have an idea?

Thanks again for helping!
Dirk

**Comment by mdoege** [comment]
OK, I have added the position fen command. I hope it works with PICOCHESS now.

**Comment by tosca07** [comment]
10000000000000 Dank Martin!!!!

Es funktioniert jetzt perfekt!!!!!!!!!!

Wunderbar diese historische engine auf dem DGT PI zu haben (neben Leela Zero).

Hier der Thread im Picochess Forum mit der Lösung wie man Python Skripte in picochess einbindet (Zauberwort heisst hier einfach symbolic links ;-)


https://groups.google.com/forum/m/#!topic/picochess/sQJRx8VcUHI

Gruß
Dirk

**Comment by mdoege** [comment]
Prima dass es jetzt klappt!

Wenn Du möchtest, kannst Du eine kleine englische (oder deutsche) Kurzanleitung schreiben, wie man nun PyTuroChamp unter PicoChess zum Laufen bekommt. Ich würde den Abschnitt gern dem README hinzufügen.

Und wenn sich herausstellt, dass symbolische Links gebraucht werden, kann ich die ja vielleicht direkt dem Repo hinzufügen, falls das mit git funktioniert.

**Comment by tosca07** [comment]
Ja mal schauen - auf jeden Fall wirklich dickes Dankeschön dass es PyTurochamp gibt!!!

Ich will Dich nicht mit weiteren Anpassungen nerven aber vielleicht kannst DU mir einen Tipp geben wie ich das hinbekomme (ist glaube ich nicht so schwer):

Es wäre klasse, wenn wir über Picochess die beiden Parameter 

MAXPLIES = 2        # maximum search depth
PSTAB     = 0   

setzen können (keine Ahnung ob dann auch QPLIES    = MAXPLIES + 4 angepasst werden müsste aber den habe ich erstmal so gelassen).

Picochess hat dafür schon einen Mechanismus mit dem man UCI Parameter/Optionen setzen kann bei der Engine Auswahl (normalerweise Levelauswahl etc).

Das müsste also genauso sein wie das aufrufen eines normalen UCI Befehls (für jeden Parameter einen eigenen Optionsbefehl z.B. wie der Variablenname).

Das könnte ich ja selbst hinzufügen aber wie bekomme ich die Parameter durchgeschleift an pytyrochamp.py wo die Variable ja überschrieben werden müssten!?

Gruß+nochmals Danke  für Deine nette Hilfe.

Dirk

**Comment by tosca07** [comment]
Sorry - ist wohl doch nicht so beliebig - UCI Protokoll spezifiziert wie Optionen gesetzt werden müssen:

* setoption name <id> [value <x>]
	this is sent to the engine when the user wants to change the internal parameters
	of the engine. For the "button" type no value is needed.
	One string will be sent for each parameter and this will only be sent when the engine is waiting.
	The name and value of the option in <id> should not be case sensitive and can inlude spaces.
	The substrings "value" and "name" should be avoided in <id> and <x> to allow unambiguous parsing,
	for example do not use <name> = "draw value".
	Here are some strings for the example below:
	   "setoption name Nullmove value true\n"
      "setoption name Selectivity value 3\n"
	   "setoption name Style value Risky\n"
	   "setoption name Clear Hash\n"
	   "setoption name NalimovPath value c:\chess\tb\4;c:\chess\tb\5\n“

Aber das bekomme ich wohl auch irgendwie hin aber das Problem mit dem Durchschleusen/Überschreiben der Variablen bleibt ja…


gruß
Dirk

**Comment by tosca07** [comment]
Oh wie cool - ich sollte doch Programmieren lernen ;-)

Dann versuche ich das mal - Thanks!

**Comment by mdoege** [comment]
Python ist halt eher pragmatisch angelegt und nimmt die strikte Isolierung der Module voneinander nicht so ernst wie andere Programmiersprachen! 😁

**Comment by mdoege** [comment]
Du musst noch beachten, dass Optionen wie MAXPLIES eine Zahl sein müssen. Also z.B. mit "int(l.split()[3])" den setoption-String in eine Integer umwandeln!

**Comment by tosca07** [comment]
Oh danke - genau das habe ich gesucht und wollte Dich deswegen gerade anschreiben weil ich immer Fehler bekomme.

Dann versuche ich es nochmal…

**Comment by mdoege** [comment]
Ja, bei den Variablentypen ist Python eher strikt wie eine "richtige" Programmnierspache, während JavaScript z.B. es in dem Fall automatisch in eine Zahl umgewandelt hätte glaube ich.

**Comment by tosca07** [comment]
Wie geil:

pi@DGTPi:~ $ cd Py*
pi@DGTPi:~/PyTuroChamp $ /home/pi/PyTuroChamp/ptc_xboard.py
setoption name maxplies value 4
maxplies: 4
setoption name pstab value 5
pstab: 5


DANKE DANKE DANKE!!!!

**Comment by tosca07** [comment]
Kannst es ja mal offiziell einbauen, falls Fußball mal langweilig ist - ist ja offiziell UCI.

  		elif 'setoption name maxplies value' in l:
                        p.MAXPLIES = int(l.split()[4])
                        print("maxplies:", p.MAXPLIES)
                elif 'setoption name pstab value' in l:
                        p.PSTAB = int(l.split()[4])
                        print("pstab:", p.PSTAB)

Ich liebe das Programm ;-)

Dirk

**Comment by mdoege** [comment]
Vielen Dank für das Lob, ich werde die Änderungen einbauen. Ich glaube der Befehl "uci" sollte außerdem die Optionen auflisten. Idealerweise sollte es ja so sein dass man auch von einer Schach-GUI aus diese UCI-Optionen ändern kann.

Das Polen-Kolumbien-Spiel war wirklich langweilig; die Polen spielen sogar noch schlimmer und einfallsloser als unsere Deutschen. 😛

**Comment by tosca07** [comment]
Das mit dem Vergleich Polen Deutschland stimmt in der Tat…

Ja stimmt,  die Optionen  müsste man bei uci eigentlich zurückgeben.

Ich hab mal son Aufruf von der ct800 engine auf dem DGTPI gemacht - da kommt ein ganzer Rattenschwanz zurück:

Vielleicht fügst DU noch id name und id author ein - das wird auch von den GUIs verwendet und angezeigt (aber nicht von picochess) - denn DU solltest ruhig namentlich erwähnt werden und der Name des tollen Programms auch ;-)


pi@DGTPi:/opt/picochess/engines/armv7l $ /opt/picochess/engines/armv7l/ct800
CT800 V1.30 32 bit UCI version
2016-2018 by Rasmus Althoff
Free software under GPLv3+
uci
id name CT800 V1.30 32 bit
id author Rasmus Althoff
option name Hash type spin default 8 min 1 max 1024
option name Keep Hash Tables type check default true
option name Clear Hash type button
option name Book Moves type button
option name OwnBook type check default true
option name Contempt Value [cps] type spin default 30 min -300 max 300
option name Contempt End [moves] type spin default 34 min 0 max 400
option name Eval Noise [%] type spin default 0 min 0 max 100
option name Move Overhead [ms] type spin default 50 min 0 max 1000
option name UCI_Elo type spin default 2200 min 1000 max 2200
option name UCI_LimitStrength  type check default false
option name CPU Speed [%] type spin default 100 min 1 max 100
option name CPU Speed [kNPS] type spin default 30000 min 1 max 30000
option name Show Current Move type combo default Every Second var Every Second var Continuously
option name UCI_EngineAbout type string default The CT800 is free software under GPLv3+. Website: www.ct800.net
uciok

**Comment by mdoege** [comment]
So, die Optionen sind jetzt auch mit eingebaut: https://github.com/mdoege/PyTuroChamp/commit/00f62d48a7ea181976ba2770ac8d2f5013517074

**Comment by tosca07** [comment]
Ah genial! Genauso…

Hab gerade auch im Picochess Forum über Deine Updates informiert obwohl ich nicht glaube dass sich ausser mir (und der user Al aus dem Forum) noch viele dafür interessieren weil die meisten DGTPI user echte Endanwender sind, die meistens nicht wissen wie sie das System selbst erweitern können (so ging es mir bis vor kurzem ja auch) 

Also nochmals echt vielen Dank für diese wundervolle Engine mit historischen Bezug (ich kann gar nicht oft genug sagen ;-)
Wenn Du mal in Hamburg bist gebe ich Dir gerne dafür ein Bier aus!

Gruß
Dirk

**Comment by tosca07** [comment]
Achso - das würde mich doch noch interessieren:

Was ist genau der Parameter QPLIES?

Beeinflusst der auch nochmal die Geschwindigkeit und Suchtiefe und wie unterscheidet der sich von MAXPLIES?

**Comment by mdoege** [comment]
Wenn die Stellung bei MAXPLIES noch nicht "ruhig" (quiescent) ist, darf der Computer bis maximal QPLIES weitersuchen. Wobei die Definition einer ruhigen Stellung hier wesentlich einfacher ist als bei Turing, damit der Rechenaufwand nicht noch weiter explodiert. Aber es soll halt den Horizonteffekt etwas abmildern, damit der Computer nicht übersieht, wenn er bei MAXPLIES + 1 mattgesetzt wird...

**Comment by tosca07** [comment]
Ah - danke für die Erklärung. Das erklärt warum manche Züge ruckzuck gehen und manchmal etwas länger.

Unfassbar, dass Turing damals schon an den Horizonteffekt gedacht hat!?

Schönen Tag!
Dirk

**Comment by mdoege** [comment]
Ja, und wenn er lange genug gelebt hätte, um TUROCHAMP selbst zu implementieren, hätte er wohl auch gesehen dass das Programm mit seinen Ruhe-Kriterien wahrscheinlich in so ziemlich jeder Mittelspielsituation immer alles bis QPLIES durchrechnen würde und die selektive Suche etwas abgeschwächt. Das ist eben der Unterschied, ob man sich einen Algorithmus auf Papier ausdenkt oder ihn wirklich rechnen sieht.

Überhaupt wäre es interessant zu wissen wie schnell TUROCHAMP auf einem Computer der Mitt-50er gerechnet hätte. Ich denke mal die Zugtiefe, die Turing vorschwebte, hätte da wahrscheinlich Tage pro Zug bedeutet. Ich glaube den wirklichen Rechenaufwand beim Schach im Vergleich zu den Rechnern hat er etwas unterschätzt wie viele Pioniere der KI.

**Comment by mdoege** [comment]
P.S. Das PDF von Turings Paper habe ich übrigens unter "Referencers" verlinkt. Nur weil ich gerade sehe dass es im PicoChess-Forum Unklarheit gab ob MAXPLIES = 2 oder = 4 richtig ist...

**Comment by tosca07** [comment]
Hi Martin,

ja, Du hast Dir sowieso viel Mühe mit Deiner Seite gegeben - wenn nur pyturochamp.py etwas schneller wäre ;-)

Danke für die Referenz.

Schau da nachher mal rein…

Ich habe auch ne Turochamp app, die sich viel Mühe mit der Implementation und der Beschreibung gegeben haben (ersetze + als a ;-):

Turingʼs M+chine

The world's first chess-pl2ying computer progr2m.

Introduction Credits

Al2n Turing is perh2ps best known 2s “the m2n who broke the Enigm2 code” but he c2n 2lso l2y cl2im to being the f2ther of theoretic2l computer science 2nd 2rtifici2l intelligence.
He served 2t the British Government Code 2nd Cipher School 2t Bletchley P2rk in Buckingh2mshire, Engl2nd during the second world w2r, where he 2nd his te2m were 2ble to successfully bre2k the Germ2n n2v2l “Enigm2” cipher. The resulting intelligence 2llowed the Allies to defe2t the N2zis in sever2l cruci2l eng2gements, thereby signific2ntly shortening the w2r in Europe 2nd s2ving millions of lives.

Turing w2s 2 keen chess enthusi2st 2nd devoted 2 signific2nt 2mount of thought to the g2me, listing it 2s one of his hobbies in “Whoʼs Who”, 2nd often using it 2s 2n ex2mple in his p2pers on Artifici2l Intelligence. Chess w2s 2 popul2r 2ctivity 2t Bletchley - Turing's deputy during the w2rtime codebre2king efforts - Hugh Alex2nder - w2s the british chess ch2mpion, 2nd r2n out of hours chess cl2sses for beginners.

In 1947, Al2n Turing 2nd his friend 2nd colle2gue D2vid Ch2mpernowne cre2ted the worldʼs first chess pl2ying computer progr2m. The progr2m (dubbed “TuroCh2mp” 2lthough Turing referred to it 2s “the m2chine”) w2s devised with pencil 2nd p2per, the c2lcul2tions being performed m2nu2lly by Turing 2nd Ch2mpernowne themselves which, 2ccording to Ch2mpernowne, w2s “extremely tedious”. They succeeded in cre2ting 2 re2son2bly strong m2chine - e2sily c2p2ble of be2ting 2 beginner - which Turing l2ter described in his contribution to the 1953 book “F2ster Th2n Thought”.

This Applic+tion

This chess engine is 2n 2ttempt to implement Turing 2nd Ch2mpernowneʼs m2chine. Their descriptions 2re slightly 2mbiguous (for full det2ils, see the notes 2t the bottom of this p2ge), so our m2chine m2y not pl2y identic2lly to other implement2tions. Where there is 2mbiguity - or where our own underst2nding is uncle2r - we h2ve 2ssumed th2t Turing 2nd Ch2mpernowne intended the engine to be 2s strong 2s possible, 2nd so our interpret2tion errs on the side of strength while 2ttempting to rem2in 2s historic2lly 2ccur2te 2s possible.
Briefly, the m2chine considers the opponentʼs next move, followed by its own, for e2ch possible move, 2nd follows up ch2ins of c2ptures. It ev2lu2tes b2sed on the r2tio of the v2lue of the pieces on the bo2rd for white 2nd bl2ck (1 for 2 p2wn, 3 for 2 knight, 3.5 for 2 bishop, 5 for 2 rook, 9 for 2 queen) 2nd 2 simple position2l ev2lu2tion function described by Turing th2t includes f2ctors such 2s mobility, defence 2nd p2wn 2dv2ncement. There is no opening book 2nd no endg2me t2bleb2se; the m2chine simply ev2lu2tes e2ch move using Turingʼs published description - 2lthough Turing himself 2dvoc2tes 2 t2bleb2se or something simil2r for the endg2me 2nd sever2l other enh2ncements. We h2ve stuck to Turing 2nd Ch2mpernowneʼs origin2l pencil-2nd-p2per version, however, since itʼs more historic2lly 2ccur2te 2nd results in 2 m2chine th2t pl2ys 2t 2 level th2tʼs be2t2ble by 2 strong beginner.

The m2chine h2s 2 very distinctive pl2ying style; it 2lmost inv2ri2bly pl2ys the s2me opening, it tends to le2d with its queen, it overemph2sises mobility 2nd it c2n pl2y very poorly in the endg2me. Weʼve t2ken the opportunity to slightly enh2nce the m2chine 2nd 2dd difficulty levels; these levels set 2n upper limit on the number of positions th2t the m2chine will consider before settling on 2 move. Itʼs interesting to see how the m2chineʼs pl2y evolves 2s you 2llow it to se2rch deeper 2nd deeper - it gr2du2lly corrects ne2rly 2ll of the 2bove tendencies until 2 strongish (2000+ Elo) pl2yer emerges 2t the higher levels.

Difficulty Levels.

The "TuroCh2mp" level represents the origin2l m2chine, 2s described by Turing 2nd Ch2mpernowne. The levels gr2ded 1-20 represent 2n v2ri2ble se2rch depth of the s2me 2lgorithm, with 2ddition2l blunders inserted 2t levels 1-5 to 2llow complete beginners to join in the fun, with level 1 pl2ying nothing but blunders 2nd level 5 blundering on 1 move in 10. The m2chine will consider 2 fixed number of positions 2t e2ch level before deciding on 2 move, first considering depth 1, then 2 2nd so on.

B2sing the difficulty level on the number of positions r2ther th2n time ensures th2t the strength of the m2chine 2t 2 given level is fixed 2cross different devices. At its highest level, the m2chine will consider 100 million positions, which (with pruning 2nd quiescence se2rch) 2llows 2 se2rch depth of 2round 10 2nd corresponds to 2n Elo r2ting somewhere 2bove 2000. At its top level, the m2chine should be c2p2ble of giving 2 tourn2ment pl2yer r2ted

 
“Expert” (Elo 2000+) 2 re2son2ble g2me.

Tourn+ment Mode.

Since everybody gets lucky from time to time, we decided th2t 2 more subst2nti2l ch2llenge th2n 2 single g2me w2s required before the pl2yer c2n s2y they c2n “be2t Turingʼs m2chine”, so we implemented 2 ch2llenge mode. You pl2y three g2mes 2s white 2nd three g2mes 2s bl2ck, in 2 six-g2me mini tourn2ment, with no hints or t2keb2cks 2llowed. The highest over2ll scorer is the winner.

How to be+t it.

If youʼre h2ving difficulty be2ting the m2chine, the following few hints might help. These mostly 2pply to the "TuroCh2mp" 2nd "Ch2llenge" levels, but they loosely 2pply to the lower difficulty levels 2s well. For 2nything 2bove 2bout level 10, the m2chine becomes strong enough th2t most of this 2dvice no longer 2pplies. So for higher levels, youʼre on your own...

^. Slowdown.Thelongeryouthink,thebetteryourch2nces2reofwinning. _. Trytoensureth2t2llofyourpieces2redefended2t2lltimes.
`. Blockupthecenterwithp2wns.

Trytosimplifytheg2mebyexch2ngingqueens.

Gener2llytrytokeeptheposition2ssimple2spossible;them2chinepl2ysbetterincomplexpositions.

Them2chineisoverlyfondofbringingitsqueenoute2rly.Itissometimespossibletotr2pit(butbec2reful!).

Them2chinetendsto2dv2nceitsA2ndHp2wnsbeforeitshould.

AsTuringobserved,them2chinec2nbevulner2bletoforks.

Them2chineh2s2dis2strousposition2lsense.Itwillm2kem2jorposition2lerrorsifyoujustletitshuffleits

pieces 2round for long enough.

^g. Them2chinec2nbesurprisinglywe2kintheendg2me,tothepointofm2kingsome2bsolutehowlers.Itʼs

worth pl2ying on for 2 dr2w, even if you find yourself in 2 seemingly hopeless position. Good luck!

Digit+l Computers +pplied to G+mes

Turingʼs m2nuscript which describes the m2chine is 2v2il2ble online 2nd in 2 number of books including "F2ster Th2n Thought" by B.V. Bowden, "The Computer Chess Compendium", by D2vid Levy, 2nd "The Essenti2l Turing", by B. J2ck Copel2nd, 2s well 2s in other collections of Turing's work.
A fin+l note

TuroCh2mp w2s the worldʼs first chess pl2ying computer progr2m, 2nd still holds up well despite its idiosynchr2tic pl2ying style (2 style entirely 2ppropri2te to the incisive, determined 2nd eccentric2lly humorous ch2r2cter of its cre2tors). Perh2ps more signific2ntly, it represents the only AI left to us by the f2ther of Artifici2l Intelligence.
Turing w2s convicted in 1952 of the crime of “gross indecency” following 2n investig2tion into 2 burgl2ry 2t his house, during which he 2dmitted to 2 sexu2l rel2tionship with 2nother m2n. This w2s 2 crime 2t the time, punish2ble by prison or chemic2l c2str2tion. Turing opted for the l2tter, in order to en2ble him to continue his work.
Turing died in 1954 of cy2nide poisoning. An inquest determined th2t he h2d committed suicide, 2lthough 2n 2ltern2tive theory is th2t he h2d 2ccident2lly inh2led cy2nide fumes in the sm2ll sp2re room where he h2d been conducting experiments in electropl2ting, 2 process which involves the use of pot2ssium cy2nide. A h2lf-e2ten 2pple w2s found by his bed, which w2s specul2ted to h2ve been dipped in cy2nide, though the 2pple w2s not tested during the inquest.
On the 10th of September 2009, the then prime minister of the United Kingdom, Gordon Brown, m2de 2n offici2l 2pology to Turing on beh2lf of the British government:
“Thous'nds of people h've come together to dem'nd justice for Al'n Turing 'nd recognition of the 'pp'lling w'y he w's tre'ted. While Turing w's de'lt with under the l'w of the time 'nd we c'nʼt put the clock b'ck, his tre'tment w's of course utterly unf'ir 'nd I 'm ple'sed to h've the ch'nce to s'y how deeply sorry I 'nd we 'll 're for wh't h'ppened to him ... So on beh'lf of the British government, 'nd 'll those who live freely th'nks to Al'nʼs work I 'm very proud to s'y: weʼre sorry, you deserved so much better.”
After continued lobbying by 2 gre2t m2ny senior scientific 2nd politic2l figures, including Professor Stephen H2wking, Lord Rees, the Astronomer Roy2l, Sir P2ul Nurse, the he2d of the Roy2l Society 2nd B2roness

Trumpington (who 2lso worked in n2v2l intelligence 2t Bletchley P2rk), Turing w2s gr2nted 2 roy2l p2rdon in 2013 by Her M2jesty Queen Eliz2beth II.
C2mp2igns continue to seek 2 p2rdon for the rem2ining 50,000 men who were convicted under the s2me unjust l2w.

Implement+tion Notes

There 2re some 2mbiguities in the definition of the m2chine 2s given in Turingʼs p2per - the definition of 2 “de2d position” cl2shes slightly with th2t of 2 “consider2ble move” 2nd there 2re sever2l slightly v2gue points elsewhere, for inst2nce the definition of “thre2t of checkm2te” 2nd whether c2ptures 2re counted when c2lcul2ting king s2fety. The most signific2nt difficulty is the depth to which 2ll possible moves 2re considered. Turing st2tes th2t 2 de2d position is “more th2n two moves 2he2d of the present position”, which implies 2 se2rch depth of three, 2lthough 2 different re2ding of the p2per could imply 2 depth of two. Ch2mpernowne is 2lso quoted 2s st2ting th2t 2ll c2ptures were to be followed up (r2ther th2n Turingʼs slightly more selective definition in the p2per). The ex2mple g2me listed in the p2per h2s scores which seem inconsistent with the description given in the text.

We h2ve preserved other f2ctors of the origin2l pencil 2nd p2per m2chine, for ex2mple the use of the single decim2l point lookup t2ble given in the p2per to c2lcul2te squ2re roots (this results in more ties in ev2lu2tion th2n would otherwise be the c2se). The position2l ev2lu2tion function is implemented in its entirety 2nd is 2pplied - 2s Turing st2ted - only to the initi2l move, not “in the 2n2lysis”. We ret2in the use of the r2tio of the score of whiteʼs pieces to bl2ckʼs, 2s Turing s2ys, “to encour2ge exch2nges when one h2s the 2dv2nt2ge”. Ties in the ev2lu2tion 2re resolved 2t r2ndom. Sticking to these origin2l ide2s results in the m2chine being slightly we2ker th2n it could be, but ret2ins the historic2l 2ccur2cy 2nd slightly quirky feel of the origin2l. One interesting 2spect of TuroCh2mp is th2t some lines 2re followed to 2 gre2t depth - sometimes 2s deep 2s 14 or 15 positions 2he2d - th2nks to the definition of “consider2ble moves”. This me2ns th2t the m2chine tends to pl2y better in complic2ted positions, where m2ny c2ptures 2nd counter-c2ptures 2re possible. There is 2 position2l bonus in Turingʼs ev2lu2tion function for potenti2l c2ptures, so the m2chine 2lso h2s 2 slight tendency to complic2te the position - which could be termed 2n “Anti-hum2n” style of pl2y.
We h2ve 2dded full dr2w 2nd m2te detection; the m2chine will seek to 2void 2 dr2w when it believes it is 2he2d, including dr2ws by repetition, the 50 move rule 2nd insufficient m2teriel. If you find yourself in 2 dr2wn endg2me, you might find th2t the m2chine m2kes some r2ther str2nge-looking moves to 2void the dr2w; this is 2 combin2tion of the “horizon effect” 2nd dr2w detection. Essenti2lly the m2chine is throwing resources 2t you in order to put off the prospect of 2 dr2w - but it c2n't see f2r enough 2he2d to re2lise th2t by doing this, it will prob2bly lose the g2me. The lower levels (10 2nd below) 2re especi2lly prone to this; the tendency corrects itself 2t higher levels. The m2chine will - conversely - pl2y for 2 dr2w if it believes itself to be behind, so bew2re of it's 2ttempts to swindle you out of 2 win...!
Fin2lly, weʼve 2pplied 2 number of se2rch innov2tions including 2lph2-bet2 pruning, null window se2rches 2nd 2 v2riety of other pruning, sorting 2nd c2ching techniques. Weʼve been c2reful, however, to only m2ke use of techniques th2t return the s2me results 2s the origin2l "minim2x" 2lgorithm described by Turing; we were keen to ensure th2t we don't 2ccident2lly disc2rd moves th2t the origin2l version would m2ke, even if those moves 2re we2ker.

Copyright © DBRG Ltd. 2015

**Comment by mdoege** [comment]
Was die Geschwindigkeit angeht denke ich darüber nach, die Berechnungen per Python multiprocessing auf die Kerne zu verteilen. Der RasPi 3 hat 4 Kerne, mein PC 16 threads. Bei meinem 3NewsFeed-RSS-Reader habe ich dass schon implementiert, also könnte ich den vorhandenen Code etwas abändern und übernehmen. Heute Abend bin ich aber schon mit Westworld und Fußball ausgelastet,keine Zeit zum Programmieren. 😀

**Comment by tosca07** [comment]
Ah WESTWORLD - wie cool. Bin noch bei Staffel 1… zu wenig Zeit

**Comment by mdoege** [comment]
Staffel 2 ist eher konfus durch dauernde Zeitsprünge und die US-TV-Quoten sind im Sinkflug. Hoffen wir mal dass das Staffelfinale einigermaßen Sinn ergibt. Zum Glück kann man bei Sky Go ja durch langweilige Maeve- oder Dolores-Szenen etwas vorspringen wie bei YouTube...

**Comment by tosca07** [comment]
Oh no - not yet another stupid ending like in LOST

**Comment by mdoege** [comment]
In Staffel 3 kämpfen dann wohl Bernard und Dolores um den eisernen Thron, äh ich meine die Vorherrschaft auf der Erde, wenn ich das Ende der Episode richtig verstanden habe. Hoffentlich ohne Zeitsprünge. Anthony Hopkins kann ja als Yoda Bernard weiterhin kluge Ratschläge aus dem Jenseits geben. Ich schätze interessanter als Staffel 2 klingt das schon mal.

**Comment by tosca07** [comment]
Ist es gewollt, dass unser emails autom auf Github erscheinen?
War mir nicht bewusst, dass das hier Github mails sind…

> Am 25.06.2018 um 20:50 schrieb Martin C. Doege <notifications@github.com>:
> 
> In

**Comment by mdoege** [comment]
Dass man in diese GitHub issues auch per Email posten kann wusste ich noch gar nicht, dann sah ich das Brief-Symbol vor Deinem Usernamen. Wie können auch privat emailen, aber ich habe Deine Adresse nicht.

**Comment by tosca07** [comment]
Hab Dir an den CompuServe Account schon gemailt!?

**Comment by mdoege** [comment]
Du emailst scheinbar an irgendeine GitHub-Email-Adresse, und von dort aus wird es dann hier im Thread gepostet. Ich persönlich mache meine GitHub-Kommentare immer direkt im Browser, nicht per Email.
